services:
  postgres:
    image: postgres:17-alpine
    container_name: cinema_postgres
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: cinema_adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
